version: '3.9'

services:
  ansible:
    build: ./ansible
    volumes:
      - ./src:/opt/app/src
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: python:3.9-alpine
    container_name: app
    working_dir: /app
    command: sleep infinity
    networks:
      - app-net
    depends_on:
      - ansible

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
