version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app-image:latest
    ports:
      - "8081:80"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    networks:
      - mynetwork

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
    networks:
      - mynetwork
  
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    networks:
      - mynetwork

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      - mynetwork

networks:
  mynetwork:

