version: '3.9'

services:
  app:
    build: ./src
    image: task2
    container_name: app
    ports:
      - "80:80"
    networks:
      - app-net

  ansible:
    build: ./ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible2
    command: ansible-playbook DockerPlaybook.yml -i inventory.hosts
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

