---
- name: Deploy Application
  hosts: localhost
  tasks:
    - name: Install Python dependencies
      pip:
        requirements: /opt/app/src/requirements.txt
        virtualenv: /opt/app/venv

    - name: Copy application files
      copy:
        src: /opt/app/src/
        dest: /app/
        remote_src: no

    - name: Run application
      shell: /opt/app/venv/bin/gunicorn -b 0.0.0.0:80 main:app
      args:
        chdir: /app
